### PR TITLE
Merging changes from timsutton osx-vm-template

### PR DESCRIPTION
**Pull request by chrisjohnson1988**
# Installing of Puppet fails

I think that the way in which [AutoPkg](https://github.com/autopkg/autopkg) is called has changed recently. Meaning that the recipe name must occur at the end of the command.

As the code stands, attempting to install puppet will fail with an error:

    virtualbox-iso: Usage: autopkg run [options] [recipe ...]
    virtualbox-iso: Run one or more recipes.

## What have I done?

I have updated the **cmtool.sh** script to match @timsutton **puppet.sh** as it  [currently exists](https://github.com/timsutton/osx-vm-templates/commit/5b772631bbc073421443499af34103ce59820bac)

### CODE REVIEW

**Comment by timsutton** [comment]
I can confirm that the current state of puppet.sh works, having just done a build last night.

A note on something I just discovered, though: PL makes available a stable URL of "puppet-latest.dmg" at https://downloads.puppetlabs.com/mac - so if you'd prefer to not bother with the logic provided by AutoPkg, that's another option. I could see osx-vm-templates moving towards that instead and letting the template pass in pinned versions or "latest" for the Puppet and Chef tools. I maintain AutoPkg and the Puppet Labs recipes for those, but removing a dependency is always nice.

**Comment by chrisjohnson1988** [comment]
Thanks Tim. I was aware that puppet labs hosted the .DMG files. It certainly seems simpler to just download and install those. Certainly something to think about.

I can also confirm that the new code builds in virtualbox.

**Comment by timsutton** [comment]
Just to clarify, the AutoPkg recipes also fetch these same downloads. At
the time I wrote the recipes however (2 years ago), they didn't have the
"latest"-named versions posted, so I wrote some additional code to list all
the items and sort them by version to pick out the highest one. Looks like
that code could be retired now.

Tim

**Comment by misheska** [comment]
Closed per Tim

**Pull request closed without merging**
